from scipy import *
from scipy.linalg import *

def solution( ) :
	print( "Here are the answers of Saddam Asmatullayev" )
	m1 = array( [ [ 1/2, 1/3 ], [ -2/7, 2/ 8 ]] )
	m2 = array( [ [ -1/3, 2/7 ], [ 2/5, -1/7 ]] )
	m3 = array( [ [ -1/5,2/3], [1/8, 3/11] ] )
	p = array( [ [ -1/30, 2/21 ], [ 41/210, -23/196 ] ] )
	I = array( [ [ 42, -56 ], [ 48, 84 ]] ) / 37
	print( "\nThis is part 1\n" )
	print( "the product of m1 and m2 is " )
	print( dot(m1,m2) )
	print( "the difference between dot(m1, m2) and p is ")
	print(dot(m1, m2)-p)
	print("so, they are equal, because the values of matrix of difference is very close to 0")
	

	print( "\nThis is part 2\n" )
	print("inverse of m1 is ")
	print(inv(m1))
	print("the matrix I is: ")
	print(I)
	print("the difference between inverse of m1 and I is ")
	print(inv(m1) - I)
	

	print( "\nThis is part 3\n" )
	a1 = dot(m1,m2)
	a2 = dot(m2,m3)
	print("this is m1.m2: ")
	print(a1)
	print("this is m2.m3: ")
	print(a2)
	print("this is (m1.m2).m3: ")
	res1 = dot(a1,m3)
	print(res1)
	print("this is m1.(m2.m3): ")
	res2 = dot(m1,a2)
	print(res2)
	print("this is (m1.m2).m3 - m1.(m2.m2): ")
	print(res1 - res2)
	
	

	print( "\nThis is part 4\n" )	
	print(" this is m1.(m2+m3): ")
	a1 = dot(m1, (m2+m3))
	print(a1)
	print(" this is m1.m2+ m1.m3: ")
	a2 = dot(m1, m2) + dot(m1, m3) 
	print(a2)
	print(" this is the difference between m1.(m2+m3) and m1.m2+ m1.m3: ")
	print(a1-a2)
	print(" this is (m1+m2).m3: ")
	a1 = dot((m1+m2), m3)	
	print(a1)
	print(" this is m1.m3 + m2.m3: ")
	a2 = dot(m1, m3) + dot(m2, m3) 
	print(a2)
	print(" this is the difference between m1.(m2+m3) and m1.m2+ m1.m3: ")
	print(a1-a2)
	

	print( "\nThis is part 5\n" )
	v = array([3.0, -1])
	print ("this is vector v: ")
	print(v)
	print ("this is m2(v): ")
	a1 = dot(m2,v)
	print(a1)
	print ("this is m1(m2(v)): ")
	b1 = dot(m1, a1)
	print(b1)
	print ("this is m1.m2: ")
	a2 = dot(m1,m2)
	print(a2)
	print ("this is (m1.m2)(v): ")
	b2 = dot(a2, v)
	print(b2)
	print("this is difference between m1(m2(v)) and (m1.m2)(v): ")
	print(b1 - b2)
	

	print( "\nThis is part 6\n" )
	a1 = det(m1)
	a2 = det(m2)
	b1 = a1*a2
	a3 = dot(m1, m2)
	b2 = det(a3)
	print ("this is det(m1): ")
	print(a1)
	print ("this is det(m2): ")
	print(a2)
	print ("this is det(m1).det(m2) ")
	print(b1)
	print ("this is det(m1.m2): ")
	print(b2)
	print ("this is difference between det(m1).det(m2) and det(m1.m2): ")
	print(b1-b2)

		
	print( "\nThis is part 7\n" )
	a1 = dot(m1, inv(m1))
	a2 = dot(inv(m1), m1)
	print("this is m1.inv(m1): ")
	print(a1)
	print("this is inv(m1).m1: ")
	print(a2)
	print("So, thery are both equal to identity matrix of size 2 ")	
			
